# -*- mode: ruby -*-
#jar 'mysql:mysql-connector-java', '5.1.9'
#jar 'postgresql:postgresql', '8.4-701.jdbc4'
jar 'com.h2database:h2', '1.2.138'
#jar 'org.apache.derby:derby' ,'10.5.3.0_1'
#jar 'org.hsqldb:hsqldb', '2.0.0'

jar 'org.slf4j:slf4j-log4j12', '1.5.2'
jar 'log4j:log4j', '1.2.14'

execute_in_phase(:initialize) do
  require 'fileutils'
  FileUtils.cp("Gemfile.pom", "pom.xml")
end
